language: csharp
script:
  - xbuild /p:Configuration=Debug ProyectoEMR.sln
before_install:
  - sudo apt-get install nunit-console
before_script:
  - nuget restore ProyectoEMR.sln
after_script:
  - nunit-console ProyectoEMRTest/bin/Debug/ProyectoEMRTest.dll
