# TP-IngenieriaSoftware2
language: csharp
solution: ProyectoEMR.sln
script:
  - ./build.sh
  - ./test.sh
  - grep "Test Results" build.log
install:
  - sudo apt-get install -y gtk-sharp2
  - nuget restore solution-name.sln
mono:
  - latest
  - 3.12.0
  - 3.10.0
