# TP-IngenieriaSoftware2
language: csharp
solution: ProyectoEMR.sln
install:
  - sudo apt-get install -y gtk-sharp2
  - nuget restore ProyectoEMR.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release ProyectoEMR.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./ProyectoEMRTest/bin/Debug/ProyectoEMRTest.dll
mono:
  - latest
  - 3.12.0
  - 3.10.0
